#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-2.0
"""Generate docs/register-index.md from docs/re/registers.yaml. RUNS ON THE HOST.

The generated file is a VIEW. Edit docs/re/registers.yaml, never the markdown,
then re-run this. `--check` verifies the committed markdown matches the YAML and
exits non-zero if it drifted, so the index cannot quietly go stale -- which is
the failure mode that makes a generated index worse than no index at all.

It also validates the YAML itself, because this file is the one place in the
tree that looks authoritative about addresses:

  - every `source:` must name a file that exists under docs/
  - no duplicate addresses
  - `confidence` must be one of the three allowed values
  - `hazard` entries must say what the consequence is, not just that there is one

The "mentioned in" appendix is recomputed from the tree at run time rather than
being stored, so it cannot disagree with what is actually there.

    usage: tools/docs/gen-register-index.py [--check]
"""
import re
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[2]
DOCS = ROOT / "docs"
SRC = DOCS / "re" / "registers.yaml"
OUT = DOCS / "register-index.md"
CONFIDENCE = {"confirmed-on-hardware", "static-analysis", "inferred"}

BLOCK_ORDER = ["cpus-arisc", "capture", "afbd", "route", "lvds", "composition",
               "proc-scaler", "detn", "ge2d", "mips", "ccu", "iommu", "ve"]


def load():
    data = yaml.safe_load(SRC.read_text())
    regs = data["registers"]
    errors, seen = [], {}
    for r in regs:
        a = r["addr"]
        if a in seen:
            errors.append(f"duplicate address {a}")
        seen[a] = r
        if r.get("confidence") not in CONFIDENCE:
            errors.append(f"{a}: confidence {r.get('confidence')!r} not in {sorted(CONFIDENCE)}")
        src = r.get("source")
        if not src:
            errors.append(f"{a}: no source")
        elif not (DOCS / src).is_file():
            errors.append(f"{a}: source {src} does not exist")
        if "hazard" in r and len(str(r["hazard"]).strip()) < 30:
            errors.append(f"{a}: hazard text must state the consequence")
    if errors:
        for e in errors:
            print(f"registers.yaml: {e}", file=sys.stderr)
        raise SystemExit(2)
    return regs


def mentions():
    """address -> number of docs/ files mentioning it. Computed, never stored."""
    # Scanned in-process, deliberately, after two bugs that were both about
    # shelling out:
    #
    #   1. The output file lives under docs/ and is full of addresses, so
    #      counting it made every run change the next run's numbers.
    #   2. Case. The docs spell the same address both ways; folding only the
    #      dict key while `grep -F` counted spellings separately meant the
    #      winner depended on set iteration order, which varies per process
    #      under string hash randomisation.
    #
    # A third followed: `grep --exclude` did not exclude, and adding the flag
    # changed the match count in a direction that makes no sense. Rather than
    # keep debugging the shell, read the files here. It is deterministic, has
    # no quoting or option-order surprises, and replaces ~1800 subprocesses
    # with one pass over the tree.
    pat = re.compile(r"0x0[0-9a-fA-F]{6,7}")
    counts = {}
    for path in sorted(DOCS.rglob("*.md")):
        if path.resolve() == OUT.resolve():
            continue
        try:
            text = path.read_text(errors="replace")
        except OSError:
            continue
        for a in {m.group(0).lower() for m in pat.finditer(text)}:
            counts[a] = counts.get(a, 0) + 1
    return {a: n for a, n in sorted(counts.items()) if n >= 3}


def render(regs, counts):
    L = []
    add = L.append
    add("<!-- GENERATED by tools/docs/gen-register-index.py -- DO NOT EDIT.")
    add("     Source of truth: docs/re/registers.yaml -->")
    add("")
    add("# Register index")
    add("")
    add("Look up an address here before grepping. Narrative lives in the journals;")
    add("this is the fact, once, with the evidence that justifies it.")
    add("")

    hz = [r for r in regs if r.get("hazard")]
    if hz:
        add("## ⚠ Hazards — read before poking anything")
        add("")
        add("These damage the board or cost a power cycle. They are not theoretical:")
        add("every one was found the hard way.")
        add("")
        add("| address | what | consequence |")
        add("| --- | --- | --- |")
        for r in sorted(hz, key=lambda r: r["addr"]):
            add(f"| `{r['addr']}` | {r['name']} | {' '.join(str(r['hazard']).split())} |")
        add("")

    add("## By block")
    add("")
    order = {b: i for i, b in enumerate(BLOCK_ORDER)}
    for block in sorted({r["block"] for r in regs}, key=lambda b: order.get(b, 99)):
        rows = sorted([r for r in regs if r["block"] == block], key=lambda r: r["addr"])
        add(f"### `{block}`")
        add("")
        add("| address | what it is | known values | confidence | evidence |")
        add("| --- | --- | --- | --- | --- |")
        for r in rows:
            vals = r.get("values") or {}
            v = "<br>".join(f"`{k}` = {w}" for k, w in vals.items()) or "—"
            note = " ".join(str(r.get("notes", "")).split())
            what = r["name"] + (f"<br>{note}" if note else "")
            conf = {"confirmed-on-hardware": "hardware",
                    "static-analysis": "static",
                    "inferred": "**inferred**"}[r["confidence"]]
            add(f"| `{r['addr']}` | {what} | {v} | {conf} | [{r['source']}]({r['source']}) |")
        add("")

    known = {r["addr"].lower() for r in regs}
    extra = sorted(a for a in counts if a not in known)
    add("## Addresses mentioned in 3+ documents but not yet catalogued")
    add("")
    add(f"{len(extra)} of them. Grepped at generation time, so this list is always")
    add("current. An address here is one the docs discuss repeatedly without any")
    add("single place saying what it *is* — that is the backlog for this file.")
    add("")
    add("| address | docs mentioning it |")
    add("| --- | --- |")
    for a in sorted(extra, key=lambda a: -counts[a])[:60]:
        add(f"| `{a}` | {counts[a]} |")
    add("")
    return "\n".join(L) + "\n"


def main():
    regs = load()
    text = render(regs, mentions())
    if "--check" in sys.argv:
        if not OUT.is_file() or OUT.read_text() != text:
            print("register-index.md is stale -- re-run tools/docs/gen-register-index.py",
                  file=sys.stderr)
            raise SystemExit(1)
        print(f"register-index.md up to date ({len(regs)} catalogued)")
        return
    OUT.write_text(text)
    print(f"wrote {OUT.relative_to(ROOT)} ({len(regs)} registers catalogued)")


if __name__ == "__main__":
    main()
