#!/usr/bin/env python3
"""Generate the H713 AV1 register-field header from swregisters-bits.txt.

The block's registers are one packed bit vector (the vendor models it as
ac_int<9276>), and 119 fields straddle 32-bit words, so a field is described
by its bit offset and width in the image rather than by (word, shift, mask):

    #define H713_AV1_<FIELD>	H713_AV1_FIELD(<bit offset>, <width>)

The driver sets fields in a shadow copy of the image and writes the image out
word by word, as the vendor's AsicFlushRegs does."""
import os, sys
here = os.path.dirname(__file__)
out = ['/* SPDX-License-Identifier: GPL-2.0 */',
       '/*',
       ' * H713 AV1 decoder register fields, generated by tools/re/av1/gen-regs-h.py',
       ' * from the vendor register model (names and widths from its debug printer,',
       ' * bit offsets from emulating its serialiser). Do not edit by hand.',
       ' */',
       '#ifndef SUNXI_H713_AV1_REGS_H_', '#define SUNXI_H713_AV1_REGS_H_', '',
       '/* The whole register image, in bytes (292 words). */',
       '#define H713_AV1_REGS_SIZE\t1168', '',
       'struct h713_av1_field {', '\tu16 lo;', '\tu16 width;', '};', '',
       '#define H713_AV1_FIELD(l, w) ((const struct h713_av1_field) { .lo = (l), .width = (w) })', '']
for l in open(os.path.join(here, 'swregisters-bits.txt')):
    f = l.split()
    name, w, lo = f[0][3:].upper(), int(f[1]), int(f[3])
    out.append(f'#define H713_AV1_{name}\tH713_AV1_FIELD({lo}, {w})')
out += ['', '#endif', '']
open(sys.argv[1], 'w').write('\n'.join(out))
print(len(out), 'lines')
