#!/bin/bash
# P1 -- does cedrus decode VP8, bit-exact? RUNS ON THE TARGET.
#
# VP8 defines exact integer reconstruction, so a host software decode is a
# correctness ORACLE and the hardware must match it bit-for-bit. That makes this
# gate the simple shape -- the same one H.264 and HEVC use -- and NOT the MPEG-2
# shape, which needs a hardware-captured baseline plus a PSNR arm because MPEG-2
# specifies only IDCT accuracy. If you are about to add a PSNR check here,
# something has gone wrong: on VP8, "close" is a failure.
#
# Two questions, and the second is not optional:
#
#   1. md5 vs the software reference -- is the output right?
#   2. VE interrupt delta           -- did the HARDWARE produce it? A software
#      fallback reproduces the reference by definition and would otherwise
#      score a clean pass while never touching the engine.
#
# This gate drives GStreamer's v4l2codecs elements, which talk straight to the
# kernel, and that is still the right arm to lead with: it is the shortest path
# to the hardware and it fails in one place if the kernel side breaks.
#
# VP8 IS NOW ALSO REACHABLE THROUGH VA-API, as of libva-v4l2-request patch 0013
# (2026-09-24) -- the statement that used to stand here, that no such path
# existed, is obsolete. All six vectors decode bit-exactly through
# `ffmpeg -hwaccel vaapi` with the VE interrupt delta to prove the engine ran.
# That arm is NOT yet wired into this script, so a VA-API-only regression would
# pass here; adding it is the same three-arm shape hevc-decode-test.sh uses
# (software control, GStreamer oracle, VA-API subject).
#
#   usage: ./vp8-decode-test.sh [vector-name ...]

set -u

DIR=$(cd "$(dirname "$0")" && pwd)
# NOT /tmp: it is a 467 MB tmpfs on this image and tmpfs is RAM.
OUT=${OUT:-/var/tmp/p1-out}
REF=${REF:-$DIR/vp8-reference-md5.txt}

# name:width:height:frames
#
# p03-p05 are the other three VP8 profiles, and they are the point of this
# ladder rather than padding: the profile field selects the reconstruction
# filter and the loop filter, both in silicon (0 bicubic+normal, 1
# bilinear+simple, 2 bilinear+normal, 3 full-pel+simple). A decoder can be
# perfect on profile 0 -- which is what essentially every real VP8 file uses --
# and wrong on the rest.
VECTORS_ALL="p01-352x288-profile0:352:288:25
p02-1280x720-profile0:1280:720:25
p03-640x480-profile1:640:480:25
p04-640x480-profile2:640:480:25
p05-640x480-profile3:640:480:25
p06-640x480-partitions:640:480:25"

mkdir -p "$OUT"

# Kernel clock at startup, so the dmesg section reports THIS run rather than
# whatever is in the ring buffer. See the note in va-decode-test.sh.
KMSG_T0=$(cut -d' ' -f1 /proc/uptime 2>/dev/null || echo 0)

hr() { printf '\n=== %s ===\n' "$1"; }

kmsg_this_run() {   # extended-regex pattern
  local buf
  buf=$(dmesg 2>/dev/null) || return 1
  printf '%s\n' "$buf" | grep -q '^\[[ ]*[0-9][0-9]*\.' || return 2
  printf '%s\n' "$buf" | awk -v t0="$KMSG_T0" '
    match($0, /^\[[ ]*[0-9]+\.[0-9]+\]/) {
      if (substr($0, RSTART + 1, RLENGTH - 2) + 0 >= t0) print
    }' | grep -iE "$1" | tail -20
}

report_kmsg() {   # extended-regex pattern
  local out rc
  out=$(kmsg_this_run "$1"); rc=$?
  case $rc in
  1) echo "  (dmesg unreadable -- run as root to see kernel messages)" ;;
  2) echo "  (dmesg carries no timestamps -- cannot scope to this run;"
     echo "   showing the last 20 matching lines UNSCOPED, which may predate it)"
     dmesg 2>/dev/null | grep -iE "$1" | tail -20 | sed 's/^/  /' ;;
  *) if [ -z "$out" ]; then
       echo "  (none since this run started, at kernel t=${KMSG_T0}s)"
     else
       printf '%s\n' "$out" | sed 's/^/  /'
     fi ;;
  esac
}

# WITHOUT THE REFERENCES THIS SCRIPT CANNOT FAIL, so it refuses to run at all.
# This is the failure mode that let the H.264 gate report a clean sweep on a
# fresh flash while comparing nothing: grep a missing file, get an empty string,
# score every vector as unverifiable, exit 0.
if [ ! -s "$REF" ]; then
  echo "FATAL: no reference hashes at $REF" >&2
  echo "" >&2
  echo "  This gate scores decoded output against per-frame and whole-file md5s." >&2
  echo "  Without them nothing here can fail, so refusing to report a result." >&2
  echo "" >&2
  echo "  Fix: copy tools/video/vp8-reference-md5.txt from the repo to $DIR/," >&2
  echo "  or run with REF=/path/to/vp8-reference-md5.txt" >&2
  echo "" >&2
  echo "  It is generated by tools/video/make-test-streams.sh on the host." >&2
  exit 2
fi

ve_irq() {
  awk '/video-codec/ { for (i = 2; i <= 5; i++) s += $i } END { print s + 0 }' \
    /proc/interrupts
}

# ivfparse, not matroskademux: the vectors are IVF because the WebM muxer is not
# reproducible and these streams have to regenerate byte-identically.
#
# Forcing NV12 is REQUIRED, not tidy. Unconstrained, the decoder negotiates
# NV12_32L32 (Allwinner 32x32 tiled) -- correct output that can never match a
# linear reference, and which reads as a decode failure if scored naively.
decode_hw() {   # stream, dst
  GST_DEBUG=${GST_DEBUG:-1} timeout 300 gst-launch-1.0 -q \
    filesrc location="$1" ! ivfparse ! v4l2slvp8dec \
    ! video/x-raw,format=NV12 ! filesink location="$2" 2>&1 | sed 's/^/     /'
}

want_md5() { grep "^$1 WHOLE" "$REF" | awk '{print $NF}'; }
want_frames() { grep "^$1 WHOLE" "$REF" | awk '{print $3}'; }

# Which frame first diverged. A whole-file mismatch says only "different"; the
# per-frame lines in the reference say WHERE, which is the difference between
# "VP8 is broken" and "frame 17 onward is broken, so it is the loop filter".
first_bad_frame() {   # file, vector, frame_size
  python3 - "$1" "$2" "$3" "$REF" <<'PY'
import hashlib, sys
path, name, fsize, ref = sys.argv[1], sys.argv[2], int(sys.argv[3]), sys.argv[4]
want = {}
for line in open(ref):
    f = line.split()
    if len(f) >= 3 and f[0] == name and f[1].startswith("frame"):
        want[int(f[1][5:])] = f[2]
n = 0
with open(path, 'rb') as fh:
    while True:
        d = fh.read(fsize)
        if len(d) < fsize: break
        if n in want and hashlib.md5(d).hexdigest() != want[n]:
            print(n); sys.exit(0)
        n += 1
print("none")
PY
}

hr "decoder"
echo "  $(ls -l /dev/video0 2>&1)"
gst-inspect-1.0 v4l2slvp8dec >/dev/null 2>&1 \
  && echo "  v4l2slvp8dec: present" \
  || { echo "  FATAL: v4l2slvp8dec not registered -- the kernel is not advertising VP8F"; exit 1; }
gst-inspect-1.0 ivfparse >/dev/null 2>&1 \
  && echo "  ivfparse:     present" \
  || { echo "  FATAL: ivfparse missing (gst-plugins-bad) -- cannot parse these vectors"; exit 1; }

hr "decode runs"
pass=0; fail=0
vectors=${*:-"p01-352x288-profile0 p02-1280x720-profile0 p03-640x480-profile1 p04-640x480-profile2 p05-640x480-profile3 p06-640x480-partitions"}

for v in $vectors; do
  spec=$(printf '%s\n' "$VECTORS_ALL" | grep "^$v:")
  [ -n "$spec" ] || { echo "  SKIP $v (not a known vector)"; continue; }
  w=$(echo "$spec" | cut -d: -f2); h=$(echo "$spec" | cut -d: -f3)
  nf=$(echo "$spec" | cut -d: -f4)

  src="$DIR/$v.ivf"
  [ -f "$src" ] || { echo "  SKIP $v (no stream at $src)"; continue; }

  printf '\n-- %s (%sx%s, %s frames)\n' "$v" "$w" "$h" "$nf"
  dst="$OUT/$v.nv12"
  rm -f "$dst"

  a=$(ve_irq)
  decode_hw "$src" "$dst"
  ve=$(( $(ve_irq) - a ))

  if [ ! -s "$dst" ]; then
    echo "     FAIL -- no output produced"
    fail=$((fail+1)); rm -f "$dst"; continue
  fi

  md5=$(md5sum "$dst" | cut -d' ' -f1)
  bytes=$(stat -c%s "$dst")
  printf '     %s bytes (want %s), md5 %s, ve+%s\n' \
    "$bytes" "$(( w * h * 3 / 2 * nf ))" "$md5" "$ve"

  if [ "$ve" -eq 0 ]; then
    echo "     FAIL -- VE interrupt count did not move: this was NOT hardware decode."
    echo "     A software fallback reproduces the reference by definition, so the"
    echo "     md5 below would have passed while the engine did nothing."
    fail=$((fail+1)); rm -f "$dst"; continue
  fi

  want=$(want_md5 "$v"); wf=$(want_frames "$v")
  if [ -z "$want" ]; then
    echo "     UNVERIFIABLE -- no '$v WHOLE' line in $REF"
    echo "     Decoded something, but nothing checked it. Counting as a failure."
    fail=$((fail+1)); rm -f "$dst"; continue
  fi

  if [ "$md5" = "$want" ]; then
    echo "     PASS -- bit-exact against the software reference ($wf frames)"
    pass=$((pass+1))
  else
    echo "     MISMATCH -- decoded, but not bit-exact (want $want)"
    echo "     first differing frame: $(first_bad_frame "$dst" "$v" "$(( w * h * 3 / 2 ))")"
    fail=$((fail+1))
  fi
  rm -f "$dst"
done

hr "kernel messages from this run"
report_kmsg "cedrus|video-codec"

printf '\nP1: %d pass, %d fail\n' "$pass" "$fail"
if [ $((pass + fail)) -eq 0 ]; then
  echo "P1: scored nothing -- no vector produced a comparable result."
  echo "    Check the .ivf streams are deployed next to the script."
  exit 1
fi
[ "$fail" -eq 0 ]
